<?php

/**
 * @file
 * A module that uses a page callback to render a form with 2 inputs
 */

 // Create  menu link
 function amalfitano_menu() {
  $items['form'] = array(
    // This will be the user-visible title
    'title' => 'Click me!',
    //This is the function that will be called when the page is rendered
    'page callback' => 'amalfitano_form_view',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

// Our callback function
function amalfitano_form_view() {
  // Calls the drupal form API to render our form
  return drupal_get_form('amalfitano_simple_form');
}

// Custom form builder function
function amalfitano_simple_form($form, &$form_state) {

  // First number field
  $form['number1'] = array(
    '#title' => t('Enter a number!'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );

  // Second number field
  $form['number2'] = array(
    '#title' => t('Enter another number!'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );

  // Create a submit button.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Add them!',
  );

  return $form;
}

function amalfitano_simple_form_validate($form, &$form_state) {
  // This will check that the user input stored in $form_state is a numeric value for both fields
  if (!is_numeric($form_state['values']['number1'])) {
    form_set_error('number1', t('enter a number please'));
  }

  if (!is_numeric($form_state['values']['number2'])) {
    form_set_error('number2', t('come on dude, thats not a number'));
  }
}

function amalfitano_simple_form_submit($form, &$form_state) {
  // Retrieve the values stored in the $form_state array, and add them
  $num1 = $form_state['values']['number1'];
  $num2 = $form_state['values']['number2'];
  $sum = $num1 + $num2;
  // Display a message to our users.
  drupal_set_message(t('The sum is: ' . $sum));
}
